TimeTable/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TimeTable.Data;
using TimeTable.Extensions;
using TimeTable.Models;

namespace TimeTable.Controllers
{
    public class GroupsController : BaseController
    {
        public GroupsController(ITimeTableContextTestable context)
            : base(context)
        {

        }

        public GroupsController()
        {

        }

        public ActionResult Index()
        {
            return View(db.Groups.ToList());
        }
        

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            var lectures = db.Lectures.ToList();
            var days = db.Weekdays.ToList();
            var times = db.LectureTimes.ToList();

            ViewBag.Days = days;
            ViewBag.Times = times;
            ViewBag.Lectures = lectures;
            return View(group);
        }

        [AdminAuthorize]
        public ActionResult Create()
        {
            return View();
        }

        [AdminAuthorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,StudentsCount")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Groups.Add(group);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(group);
        }

        [AdminAuthorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        [AdminAuthorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,StudentsCount")] Group group)
        {
            if (ModelState.IsValid)
            {
                db.Entry(group).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(group);
        }

        [AdminAuthorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Group group = db.Groups.Find(id);
            if (group == null)
            {
                return HttpNotFound();
            }
            return View(group);
        }

        [AdminAuthorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Group group = db.Groups.Find(id);
            db.Groups.Remove(group);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TimeTable/Controllers/LecturesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TimeTable.Data;
using TimeTable.Models;
using TimeTable.ViewModels;
using TimeTable.Extensions;
using TimeTable.Services;
using System.Text;

namespace TimeTable.Controllers
{

    public class LecturesController : BaseController
    {
        private readonly ISwapService swapService;
        private readonly IGenerateService generateService;
        
        public LecturesController(ISwapService swapService, IGenerateService generateService)
        {
            this.swapService = swapService;
            this.generateService = generateService;
        }

        public LecturesController(ITimeTableContextTestable context)
            : base(context)
        {

        }

        public LecturesController()
        {
        }

        public ActionResult Index()
        {
            return View(db.Lectures.ToList());
        }
        /// <summary>
        /// Metodas sugeneruojantis tvarkaraštį
        /// </summary>
        /// <returns>Lecture indexview su laikais</returns>
        [HttpPost]
        [AdminAuthorize]
        [ValidateAntiForgeryToken]
        public ActionResult GenerateTable()
        {
            try
            {
                generateService.Validate();
                generateService.Generate();
                return RedirectToAction("Index");
            }
            catch (NullReferenceException e)
            {
                ViewBag.Error = "Duombazėje nėra tokių indeksų: " + e.Source;

                return RedirectToAction("Index", "Home");
            }
        }
        /// <summary>
        /// Metodas, kuris apkeičia dviejų paskaitų laikus, jeigu tai yra įmanoma
        /// </summary>
        /// <param name="ID1">Pirmos Lecture ID</param>
        /// <param name="ID2">Antros Lecture ID</param>
        /// <returns>Lecture index view</returns>
        [HttpPost]
        [AdminAuthorize]

        public ActionResult Swap2Lectures(int ID1, int ID2)
        {
            try
            {
                Log log = new Log();
                string msg = "";
                Lecture first = db.Lectures.Find(ID1);
                log.OldLectureFirstTeacherID = first.TeacherID;
                log.OldLectureFirstClassroomID = first.ClassRoomID;
                Lecture second = db.Lectures.Find(ID2);
                log.OldLectureSecondTeacherID = second.TeacherID;
                log.OldLectureSecondClassroomID = second.ClassRoomID;
                string info = first.ToString();
                string info2 = second.ToString();
                swapService.Swap2Lectures(ID1, ID2, ref msg);
                if (msg.Contains("successful"))
                {
                    log.isUndoable = true;
                }
                else log.isUndoable = false;
                log.LogItem = string.Format("Lecture1: {0}\n Lecture 2: {1}\n Message: {2}\n", info, info2, msg);
                log.FirstLectureID = ID1;
                log.SecondLectureID = ID2;
                db.Logs.Add(log);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            catch (NullReferenceException e)
            {
                ViewBag.Error = "Duombazėje nėra tokių indeksų: " + e.Source;

                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [AdminAuthorize]
        public ActionResult Undo(int logItemID)
        {
            try
            {
                swapService.Undo(logItemID);
                return RedirectToAction("Index", "Home");
            }
            catch (NullReferenceException e)
            {
                ViewBag.Error = "Duombazėje nėra tokio log indekso: " + e.Source;

                return RedirectToAction("Index", "Home");
            }
        }

        [AdminAuthorize]
        public ActionResult GetLog()
        {
            int count = db.Logs.Count();
            if (count > 10)
                return Json(db.Logs.OrderBy(x => x.ID).Select(x => new { x.LogItem, x.ID, x.isUndoable }).Skip(count - 10).Take(10).ToArray().Reverse(), JsonRequestBehavior.AllowGet);
            else
                return Json(db.Logs.OrderBy(x => x.ID).Select(x => new { x.LogItem, x.ID, x.isUndoable }).ToArray().Reverse(), JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        [AdminAuthorize]
        public ActionResult GetAvailableChanges(int lectureToSwapID, bool swapTeacher, bool swapClassroom)
        {
            try
            {
                List<Object> list = swapService.FindPossibleChanges(lectureToSwapID, swapTeacher, swapClassroom);
                return Json(list, JsonRequestBehavior.AllowGet);
    
            }
            catch (NullReferenceException e)
            {
                ViewBag.Error = "Duombazėje nėra tokio log indekso: " + e.Source;

                return RedirectToAction("Index", "Home");
            }
        }


        /// <summary>
        /// Metodas priskiriantis paskaitai naują laiką
        /// </summary>
        /// <param name="lectureId">Lecture ID</param>
        /// <param name="newLectureTimeId">Naujo LectureTime ID</param>
        /// <param name="newLectureDayId">Naujo Weeday ID</param>
        /// <returns>Lecture index view</returns>
        [HttpPost]
        [AdminAuthorize]
        public ActionResult ChangeLectureTime(int lectureId, int newLectureTimeId, int newLectureDayId)
        {
            try
            {
                Log log = new Log();
                Lecture first = db.Lectures.Find(lectureId);
                log.OldLectureFirstTeacherID = first.TeacherID;
                log.OldLectureFirstClassroomID = first.ClassRoomID;
                log.OldLectureTimeID = first.LectureTimeID;
                log.OldWeekdayID = first.WeekdayID;
                string info = first.ToString();
                string msg = "";
                swapService.ChangeLectureTime(lectureId, newLectureTimeId, newLectureDayId, ref msg);
                if (msg.Contains("successful"))
                {
                    log.isUndoable = true;
                }
                else log.isUndoable = false;
                log.LogItem = string.Format("Lecture: {0} New day: {1} New start time: {2} Message: {3}", info, db.Weekdays.Where(x => x.ID == newLectureDayId).Select(x => x.Name).FirstOrDefault(), db.LectureTimes.Where(x => x.ID == newLectureTimeId).Select(x => x.Start).FirstOrDefault(), msg);
                log.FirstLectureID = lectureId;
                db.Logs.Add(log);
                db.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            catch (NullReferenceException e)
            {
                ViewBag.Error = "Duombazėje nėra tokių indeksų: " + e.Source;

                return RedirectToAction("Index", "Home");
            }
        }



        /// <summary>
        /// Grazina informacija apie duombazės įrašą
        /// </summary>
        /// <param name="id"></param>
        /// <returns>Informacija apie irasa</returns>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lecture lecture = db.Lectures.Find(id);
            if (lecture == null)
            {
                return HttpNotFound();
            }
            return View(lecture);
        }

        /// <summary>
        /// Sukuria irasa duombazėje
        /// </summary>
        /// <returns>View modeli</returns>
        /// [AdminAuthorize]
        public ActionResult Create()
        {
            List<SelectListItem> types = new List<SelectListItem>();
            types.Add(new SelectListItem()
            {
                Text = "Teorinė",
                Value = "Teorinė"
            });
            types.Add(new SelectListItem()
            {
                Text = "Praktinė",
                Value = "Praktinė"
            });
            types.Add(new SelectListItem()
            {
                Text = "-",
                Value = "",
                Selected = true
            });

            LectureViewModel model = new LectureViewModel()
            {
                Teachers = db.Teachers.ToList().Select(x => new SelectListItem()
                {
                    Text = string.Format("{0} {1}", x.FirstName, x.LastName),
                    Value = x.ID.ToString()
                }).ToList().AddDefaultItem(),

                ClassRooms = db.ClassRooms.ToList().Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.ID.ToString()
                }).ToList().AddDefaultItem(),

                Groups = db.Groups.ToList().Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.ID.ToString()
                }).ToList().AddDefaultItem(),

                Subjects = db.Subjects.ToList().Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.ID.ToString()
                }).ToList().AddDefaultItem(),

                LectureTimes = db.LectureTimes.ToList().Select(x => new SelectListItem()
                {
                    Text = string.Format("{0} - {1}", x.Start, x.End),
                    Value = x.ID.ToString()
                }).ToList().AddDefaultItem(),

                Weekdays = db.Weekdays.ToList().Select(x => new SelectListItem()
                {
                    Text = x.Name,
                    Value = x.ID.ToString()
                }).ToList().AddDefaultItem(),

                TypesList = types
            };

            return View(model);
        }

        /// <summary>
        /// Sukuria atributus irasui
        /// </summary>

TimeTable/Controllers/SubjectsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using TimeTable.Data;
using TimeTable.Extensions;
using TimeTable.Models;

namespace TimeTable.Controllers
{
    public class SubjectsController : BaseController
    {

        // GET: Subjects
        public ActionResult Index()
        {
            return View(db.Subjects.ToList());
        }

        // GET: Subjects/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        [AdminAuthorize]
        public ActionResult Create()
        {
            return View();
        }

        [AdminAuthorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Code")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                db.Subjects.Add(subject);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(subject);
        }

        [AdminAuthorize]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        [AdminAuthorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Code")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                db.Entry(subject).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(subject);
        }

        [AdminAuthorize]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Subject subject = db.Subjects.Find(id);
            if (subject == null)
            {
                return HttpNotFound();
            }
            return View(subject);
        }

        [AdminAuthorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Subject subject = db.Subjects.Find(id);
            db.Subjects.Remove(subject);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

TimeTable/Views/Lectures/Create.cshtml
@model TimeTable.ViewModels.LectureViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Lecture</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TeacherID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.TeacherID, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.DropDownList("TeacherID", "-")*@
                @Html.DropDownListFor(x => x.TeacherID, Model.Teachers, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TeacherID, "", new { @class = "text-danger" })
                
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GroupID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.GroupID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(x => x.GroupID, Model.Groups, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GroupID, "", new { @class = "text-danger" })
                @*@Html.DropDownList("GroupID", "-")*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClassRoomID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.ClassRoomID, new { htmlAttributes = new { @class = "form-control" } })*@
                @Html.DropDownListFor(x => x.ClassRoomID, Model.ClassRooms, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClassRoomID, "", new { @class = "text-danger" })
                @*@Html.DropDownList("ClassRoomID", "-")*@
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LectureTimeID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.LectureTimeID, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.DropDownList("LectureTimeID", "-")*@
                @Html.DropDownListFor(x => x.LectureTimeID, Model.LectureTimes, new { @disabled = "disabled", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LectureTimeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WeekdayID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.WeekdayID, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.DropDownList("WeekdayID", "-")*@
                @Html.DropDownListFor(x => x.WeekdayID, Model.Weekdays, new { @disabled = "disabled", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.WeekdayID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.SubjectID, new { htmlAttributes = new { @class = "form-control" } })*@
                @*@Html.DropDownList("SubjectID", "-")*@
                @Html.DropDownListFor(x => x.SubjectID, Model.Subjects, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.Type, Model.TypesList, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsPCRequired, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsPCRequired, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsPCRequired, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

TimeTable/Views/Lectures/Delete.cshtml
@model TimeTable.Models.Lecture

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Lecture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TeacherID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeacherID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClassRoomID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassRoomID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LectureTimeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LectureTimeID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WeekdayID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WeekdayID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubjectID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubjectID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPcRequired)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPcRequired)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TimeTable/Views/Lectures/Details.cshtml
@model TimeTable.Models.Lecture

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Lecture</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.TeacherID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TeacherID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GroupID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GroupID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ClassRoomID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClassRoomID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LectureTimeID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LectureTimeID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.WeekdayID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.WeekdayID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SubjectID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SubjectID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsPcRequired)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPcRequired)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

TimeTable/Views/Lectures/Index.cshtml
@model IEnumerable<TimeTable.Models.Lecture>

@{
    ViewBag.Title = "List of all lectures";
}

@if (ViewBag.Error != null)
{
    <h3 style="color:red">@ViewBag.Error</h3>
}


<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<p>
    @using (Html.BeginForm("GenerateTable", "Lectures"))
    {
        @Html.AntiForgeryToken()
        <button type="submit" class="btn btn-success">Generate table</button>
    }
    
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.TeacherID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.GroupID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ClassRoomID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LectureTimeID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.WeekdayID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SubjectID)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsPcRequired)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(string.Join(" ", item.Teacher.FirstName, item.Teacher.LastName), "Details", "Teachers", new { id = item.TeacherID }, new { })
        </td>
        <td>
            @Html.ActionLink(item.Group.Name, "Details", "Groups", new { id = item.GroupID }, new { })
        </td>
        <td>
            @Html.ActionLink(item.ClassRoom.Name, "Details", "ClassRooms", new { id = item.ClassRoomID }, new { })
        </td>
        <td>
            @if (item.LectureTime != null)
            {
                @Html.ActionLink(string.Join(" - ", item.LectureTime.Start.ToString(@"hh\:mm"),
                item.LectureTime.End.ToString(@"hh\:mm")), "Details", "LectureTimes", new { id = item.LectureTimeID }, new { })
            }
        </td>
        <td>
            @if (item.Weekday != null)
            {
                @Html.ActionLink(item.Weekday.Name, "Details", "Weekdays", new { id = item.WeekdayID }, new { })
            }
        </td>
        <td>
            @Html.ActionLink(item.Subject.Name, "Details", "Subjects", new { id = item.SubjectID }, new { })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsPcRequired)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>